-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
local tiles =
{
    {
        x = 2,
        y = 1,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 1,
        zone = [[om_hall]],
        variant = 0,
    },
    {
        x = 2,
        y = 2,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 2,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "safeRoomFinal",
            "noguard",
        },
    },
    {
        x = 2,
        y = 3,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 3,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 3,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 4,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 4,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
            "safeRoomLockDoor",
        },
    },
    {
        x = 4,
        y = 4,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 5,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 5,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 5,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 6,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 6,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 6,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 7,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 7,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 7,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 8,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 8,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 8,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 2,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 1,
        zone = [[om_hall]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 1,
        y = 4,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 3,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 2,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 1,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 5,
        y = 4,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 5,
        y = 3,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 5,
        y = 2,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 5,
        y = 1,
        zone = [[om_hall]],
        variant = 0,
        impass = 1,
        cover = 1,
    },
}
local walls =
{
    {
        x = 4,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 1,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 2,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 1,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 2,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 1,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 2,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 1,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 4,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 2,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 9,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 9,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 4,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 9,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 4,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 5,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 6,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 3,
        y = 4,
        wallIndex = [[blast_door]],
        dir = 2,
    },
    {
        x = 3,
        y = 5,
        wallIndex = [[blast_door]],
        dir = 6,
    },
}
local units =
{
    {
        maxCount = 1,
        spawnChance = 1,
        {
            {
                x = 3,
                y = 1,
                template = [[lab_safe]],
                unitData =
                {
                    facing = 2,
                    tags =
                    {
                        "safeRoomStorage",
                    }
                },
            },
            1,
        },
    },
    bounty_target =
    {
        spawnChance = 1,
        maxCount = 1,
        {
            {
                x = 2,
                y = 5,
                template = [[npc_bounty_target]],
                unitData =
                {
                    facing = 1,
                    traits={nopatrol=true,mm_fixnopatrolfacing=true,mm_nopatrolchange=true},
                    tags =
                    {
                        "bounty_target",
                    },
                },
            },
            1,
        },
    },
    bodyguard =
    {
        spawnChance = 1,
        maxCount = 1,
        {
            {
                x = 4,
                y = 8,
                template = [[npc_guard]],
                unitData =
                {
                    facing = 5,
                    traits={nopatrol=true,mm_fixnopatrolfacing=true,mm_nopatrolchange=true},
                },
            },
            1,
        },
    },
}
local decos =
{
    {
        x = 3,
        y = 1,
        kanim = [[decor_finalhall_1x1_walllight1]],
        facing = 2,
    },
    {
        x = 5,
        y = 4,
        kanim = [[decor_finalhall_1x1_walllight1]],
        facing = 6,
    },
    {
        x = 1,
        y = 4,
        kanim = [[decor_finalhall_1x1_walllight1]],
        facing = 6,
    },
    {
        x = 5,
        y = 2,
        kanim = [[decor_engineroom_1x1_gear3]],
        facing = 2,
    },
    {
        x = 1,
        y = 2,
        kanim = [[decor_engineroom_1x1_gear3]],
        facing = 6,
    },
    {
        x = 1,
        y = 3,
        kanim = [[decor_engineroom_1x1_gear3]],
        facing = 6,
    },
    {
        x = 4,
        y = 6,
        kanim = [[ftm_lab_coats]],
        facing = 4,
    },
    {
        x = 3,
        y = 8,
        kanim = [[prefinal_1x1_floordecal1]],
        facing = 4,
    },
    {
        x = 3,
        y = 7,
        kanim = [[prefinal_1x1_floordecal1]],
        facing = 4,
    },
    {
        x = 3,
        y = 6,
        kanim = [[prefinal_1x1_floordecal1]],
        facing = 4,
    },
    {
        x = 3,
        y = 5,
        kanim = [[prefinal_1x1_floordecal1]],
        facing = 4,
    },
    {
        x = 4,
        y = 5,
        kanim = [[decor_finalhall_1x1_walllight1]],
        facing = 2,
    },
    {
        x = 2,
        y = 5,
        kanim = [[decor_finalhall_1x1_walllight1]],
        facing = 2,
    },
    {
        x = 2,
        y = 7,
        kanim = [[ftm_lab_sink1]],
        facing = 0,
    },
    {
        x = 1,
        y = 1,
        kanim = [[decor_engineroom_1x1_gear4]],
        facing = 6,
    },
    {
        x = 5,
        y = 3,
        kanim = [[decor_engineroom_1x1_gear3]],
        facing = 6,
    },
    {
        x = 1,
        y = 4,
        kanim = [[decor_engineroom_1x1_gear3]],
        facing = 6,
    },
    {
        x = 5,
        y = 4,
        kanim = [[decor_engineroom_1x1_gear3]],
        facing = 6,
    },
    {
        x = 5,
        y = 2,
        kanim = [[decor_finalhall_2x1_wallgear3]],
        facing = 4,
    },
    {
        x = 1,
        y = 1,
        kanim = [[decor_finalhall_1x1_wallgear4]],
        facing = 2,
    },
    {
        x = 5,
        y = 1,
        kanim = [[decor_finalhall_1x1_wallgear6]],
        facing = 2,
    },
    {
        x = 5,
        y = 1,
        kanim = [[decor_engineroom_1x1_gear4]],
        facing = 2,
    },
    {
        x = 3,
        y = 2,
        kanim = [[prefinal_1x1_floordecal2]],
        facing = 0,
    },
    {
        x = 1,
        y = 3,
        kanim = [[decor_finalhall_2x1_wallgear3]],
        facing = 0,
    },
}
local lights =
{
}
local sounds =
{
}
local export =
{
    cgraph =
    {
        edges =
        {
            {
                id0 = 100,
                x0 = 2,
                y0 = 5,
                id1 = 1,
                x1 = 1,
                y1 = 5,
            },
            {
                id0 = 100,
                x0 = 2,
                y0 = 6,
                id1 = 2,
                x1 = 1,
                y1 = 6,
            },
            {
                id0 = 100,
                x0 = 2,
                y0 = 7,
                id1 = 3,
                x1 = 1,
                y1 = 7,
            },
            {
                id0 = 100,
                x0 = 2,
                y0 = 8,
                id1 = 4,
                x1 = 1,
                y1 = 8,
            },
            {
                id0 = 5,
                x0 = 5,
                y0 = 8,
                id1 = 100,
                x1 = 4,
                y1 = 8,
            },
            {
                id0 = 6,
                x0 = 5,
                y0 = 7,
                id1 = 100,
                x1 = 4,
                y1 = 7,
            },
            {
                id0 = 7,
                x0 = 5,
                y0 = 6,
                id1 = 100,
                x1 = 4,
                y1 = 6,
            },
            {
                id0 = 8,
                x0 = 5,
                y0 = 5,
                id1 = 100,
                x1 = 4,
                y1 = 5,
            },
            {
                id0 = 100,
                x0 = 2,
                y0 = 8,
                id1 = 9,
                x1 = 2,
                y1 = 9,
            },
            {
                id0 = 100,
                x0 = 3,
                y0 = 8,
                id1 = 10,
                x1 = 3,
                y1 = 9,
            },
            {
                id0 = 100,
                x0 = 4,
                y0 = 8,
                id1 = 11,
                x1 = 4,
                y1 = 9,
            },
            {
                id0 = 12,
                x0 = 2,
                y0 = 0,
                id1 = 100,
                x1 = 2,
                y1 = 1,
            },
            {
                id0 = 13,
                x0 = 3,
                y0 = 0,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 14,
                x0 = 4,
                y0 = 0,
                id1 = 100,
                x1 = 4,
                y1 = 1,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 4,
                id1 = 1,
                x1 = 1,
                y1 = 5,
            },
            {
                id0 = 15,
                x0 = 1,
                y0 = 0,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 100,
                x0 = 5,
                y0 = 4,
                id1 = 8,
                x1 = 5,
                y1 = 5,
            },
            {
                id0 = 16,
                x0 = 6,
                y0 = 1,
                id1 = 100,
                x1 = 5,
                y1 = 1,
            },
            {
                id0 = 17,
                x0 = 6,
                y0 = 2,
                id1 = 100,
                x1 = 5,
                y1 = 2,
            },
            {
                id0 = 18,
                x0 = 6,
                y0 = 3,
                id1 = 100,
                x1 = 5,
                y1 = 3,
            },
            {
                id0 = 19,
                x0 = 6,
                y0 = 4,
                id1 = 100,
                x1 = 5,
                y1 = 4,
            },
            {
                id0 = 20,
                x0 = 5,
                y0 = 0,
                id1 = 100,
                x1 = 5,
                y1 = 1,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 4,
                id1 = 21,
                x1 = 0,
                y1 = 4,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 3,
                id1 = 22,
                x1 = 0,
                y1 = 3,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 2,
                id1 = 23,
                x1 = 0,
                y1 = 2,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 1,
                id1 = 24,
                x1 = 0,
                y1 = 1,
            },
            {
                id0 = 1,
                x0 = 1,
                y0 = 5,
                id1 = 100,
                x1 = 1,
                y1 = 4,
            },
            {
                id0 = 21,
                x0 = 0,
                y0 = 4,
                id1 = 100,
                x1 = 1,
                y1 = 4,
            },
            {
                id0 = 22,
                x0 = 0,
                y0 = 3,
                id1 = 100,
                x1 = 1,
                y1 = 3,
            },
            {
                id0 = 23,
                x0 = 0,
                y0 = 2,
                id1 = 100,
                x1 = 1,
                y1 = 2,
            },
            {
                id0 = 15,
                x0 = 1,
                y0 = 0,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 24,
                x0 = 0,
                y0 = 1,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 8,
                x0 = 5,
                y0 = 5,
                id1 = 100,
                x1 = 5,
                y1 = 4,
            },
            {
                id0 = 19,
                x0 = 6,
                y0 = 4,
                id1 = 100,
                x1 = 5,
                y1 = 4,
            },
            {
                id0 = 18,
                x0 = 6,
                y0 = 3,
                id1 = 100,
                x1 = 5,
                y1 = 3,
            },
            {
                id0 = 17,
                x0 = 6,
                y0 = 2,
                id1 = 100,
                x1 = 5,
                y1 = 2,
            },
            {
                id0 = 16,
                x0 = 6,
                y0 = 1,
                id1 = 100,
                x1 = 5,
                y1 = 1,
            },
            {
                id0 = 20,
                x0 = 5,
                y0 = 0,
                id1 = 100,
                x1 = 5,
                y1 = 1,
            },
        },
    },
    width = 5,
    height = 8,
    version = 1,
    tiles = tiles,
    walls = walls,
    units = units,
    decos = decos,
    lights = lights,
    sounds = sounds,
}
return export
